const fourRowGame = {
  wrapperParentDiv: {
    flexGrow: 1,
  },
  wrapperPaperForHeader: {
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    opacity: 1,
    width: "100%",
    height: "50px",
    position: "fixed",
    top: 0,
  },
  wrapperPaperForGameDash: {
    background: "#F5F5F5 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #F7F7F7",
    borderRadius: "30px",
    opacity: 1,
    width: "calc(100% - 40%)",
    height: "calc(100% - 22%)",
    margin: "auto",
    marginTop: "60px",
  },
  wrapperDivForGameTournamentTxt: {
    paddingTop: "10%",
    textAlign: "center",
    letterSpacing: 0,
    color: "#424242",
    opacity: 1,
    fontFamily: "sans-serif",
    fontSize: "18px",
    fontWeight: "500",
  },
  wrapperDivCongratulationTxt: {
    margin: "2% 0px",
    textAlign: "center",
    letterSpacing: "0px",
    color: "#FF6600",
    opacity: 1,
    fontSize: "22px",
    fontFamily: "sans-serif",
    fontWeight: "700",
  },
  wrapperDivWonTournamentTxt: {
    textAlign: "center",
    letterSpacing: "0px",
    color: "#505351",
    opacity: 1,
    fontSize: "13px",
    fontFamily: "sans-serif",
    fontWeight: 400,
  },
  wrapperDivPlayerOneTxt: {
    background: "#DCF6E4 0% 0% no-repeat padding-box",
    border: "1px solid #70707026",
    borderRadius: "15px",
    opacity: 1,
    marginTop: "18%",
    display: "flex",
    margin: "18% 12% 0%",
    height: "11vh",
  },
  wrapperDivPlayerTwoTxt: {
    background: "#F6EFD5  0% 0% no-repeat padding-box",
    border: "1px solid #70707026",
    borderRadius: "15px",
    opacity: 1,
    margin: "2% 12%",
    display: "flex",
    height: "11vh",
  },
  playerOne: {
    height: "36px",
    width: "36px",
    backgroundColor: "white",
    borderRadius: "50%",
    display: "inline-block",
    border: "8px solid #37AC5D",
    display: "block",
    margin: "5% 6%",
  },
  playerTwo: {
    height: "36px",
    width: "36px",
    backgroundColor: "white",
    borderRadius: "50%",
    display: "inline-block",
    border: "8px solid #F8D146",
    display: "block",
    margin: "5% 6%",
  },
  playerStyleTxt: {
    textAlign: "left",
    letterSpacing: "0px",
    color: "#424242",
    margin: "4px 0px",
    opacity: 0.56,
    fontFamily: "sans-serif",
    fontSize: "8px",
  },
  playerNameTxt: {
    textAlign: "left",
    letterSpacing: "0px",
    color: "#424242",
    opacity: 1,
    fontFamily: "sans-serif",
    fontSize: "14px",
    fontWeight: 400,
  },
  startOrUndoStyleBtn: {
    background: "#4B7BFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #70707026",
    borderRadius: "10px",
    opacity: 1,
    width: "75%",
    padding: "15px",
    textAlign: "center",
    letterSpacing: "0px",
    color: "#FFFFFF",
    fontSize: "14px",
    textTransform: "none",
    fontWeight: "500",
    margin: "2% 0%",
    "&:hover,&:focus": {
      background: "#4B7BFF 0% 0% no-repeat padding-box",
      boxShadow: "0px 3px 6px #00000029",
    },
  },
  endGameStyleBtn: {
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #4B7BFF26",
    borderRadius: "10px",
    opacity: 1,
    width: "75%",
    padding: "15px",
    textAlign: "center",
    letterSpacing: "0px",
    color: "#CC0000",
    textTransform: "none",
    fontSize: "16px",
    fontWeight: "700",
    "&:hover,&:focus": {
      background: "#FFFFFF 0% 0% no-repeat padding-box",
      boxShadow: "0px 3px 6px #00000029",
    },
  },
  tableStyle: {
    margin: "3px auto",
    borderSpacing: "0px 0px",
    background: "#84A4FC",
    borderRadius: "12px",
  },
  arrowStyleOfBackBtn: {
    display: "grid",
    margin: "0.8% 3%",
},
playerstxt: {
    flex: "none",
    margin: "1% -15%",
}
};

export default fourRowGame;
