const simpleInputBox = {
        input: {
            font: "inherit",
            color: "currentColor",
            width: "100%",
            border: "0px",
            height: "1.1876em",
            margin: "0px -2px",
            display: "block",
            padding: "6px 40px 7px 7px",
            borderBottom: "1px solid black",
            background: "none",
            boxSizing: "content-box",
            letterSpacing: "inherit",
            '& .MuiInputBase-input':{
                font: "inherit",
                color: "currentColor",
                width: "100%",
                border: "0",
                height: "1.1876em",
                margin: "0",
                display: "block",
                padding: "6px 0 7px 10px",
                minWidth: "0",
                background: "none",
                boxSizing: "content-box",
                letterSpacing: "inherit",
                animationDuration: "10ms",
            },
        },
        playerOne: {
            height: "40px",
            width: "40px",
            backgroundColor: "white",
            borderRadius: "50%",
            display: "inline-block",
            border: "8px solid #37AC5D",
            display: "block",
            transform: "translate(-100% , -100%)",
        },
        playerTwo: {
            height: "40px",
            width: "40px",
            backgroundColor: "white",
            borderRadius: "50%",
            display: "inline-block",
            border: "8px solid #F8D146",
            display: "block",
            transform: "translate(-100% , -100%)",
        },
        playerAdditioalData: {
            height: "40px",
            width: "40px",
            backgroundColor: "white",
            borderRadius: "50%",
            display: "inline-block",
            border: "8px solid #B1C4F9",
            display: "block",
            transform: "translate(-100% , -100%)",
        },
        wrapperStyleForLabelText: {
            display: "flex",
            margin: "0px 7%",
        }
}

export default simpleInputBox;