const confirmationDialogueBox = {
  noOfPlayerStyle: {
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #F7F7F7",
    borderRadius: "30px",
    opacity: 1,
    width: "30%",
    height: "60%",
    minWidth: "300px",
  },
  playerWhoStartStyle: {
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #F7F7F7",
    borderRadius: "30px",
    opacity: 1,
    width: "30%",
    height: "60%",
    minWidth: "300px",
  },
  cardStyleOfradio: {
    background: "#EFF3FF 0% 0% no-repeat padding-box",
    border: "1px solid #70707026",
    borderRadius: "10px",
    margin: "2px",
    opacity: 1,
    marginRight: "-11px",
  },
  cancelBtStyle: {
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #4B7BFF26",
    borderRadius: "10px",
    opacity: 1,
    color: "#4B7BFF",
    width: "45%",
    padding: "13px 0px",
    margin: "5% 3%",
    "&:hover,&:focus": {
      background: "#FFFFFF 0% 0% no-repeat padding-box",
      boxShadow: "0px 3px 6px #00000029",
    },
  },
  okBtnStyle: {
    background: "#4B7BFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #70707026",
    borderRadius: "20px",
    opacity: 1,
    color: "white",
    float: "right",
    borderRadius: "10px",
    width: "45%",
    margin: "5% 0%",
    opacity: 1,
    padding: "13px 0px",
    "&:hover,&:focus": {
      background: "#4B7BFF 0% 0% no-repeat padding-box",
      boxShadow: "0px 3px 6px #00000029",
    },
  },
};

export default confirmationDialogueBox;
