const detailAdditionPageStyle = {
  wrapperDivOfHeader: {
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    opacity: 1,
    width: "100%",
    height: "7%",
    position: "absolute",
  },
  wrapperDivOfDetail: {
    top: "54%",
    left: "50%",
    width: "calc(100% - 68%)",
    minWidth: "350px",
    border: "1px solid #F7F7F7",
    height: "80vh",
    opacity: 1,
    position: "absolute",
    transform: "translate(-50%, -50%)",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 10px #00000029",
    borderRadius: "30px",
  },
  divForFirstPlayer: {
    background: "#DCF6E4 0% 0% no-repeat padding-box",
    border: "1px solid #70707026",
    borderRadius: "15px",
    opacity: 1,
    height: "16%",
    margin: "7% 10%",
    overflow: "hidden",
    padding: "0% 16%",
  },
  divForSecondPlayer: {
    background: "#F6EFD5 0% 0% no-repeat padding-box",
    border: "1px solid #70707026",
    borderRadius: "15px",
    opacity: 1,
    height: "16%",
    margin: "-6% 9%",
    overflow: "hidden",
    padding: "0% 16%",
  },
  divForNoOfPlayer: {
    background: "#DCF6E4 0% 0% no-repeat padding-box",
    border: "1px solid #70707026",
    borderRadius: "15px",
    opacity: 1,
    height: "16%",
    margin: "7% 10%",
    overflow: "hidden",
    padding: "0% 16%",
  },
  divForWhoStart: {
    background: "#EFF3FF 0% 0% no-repeat padding-box",
    border: "1px solid #70707026",
    borderRadius: "15px",
    opacity: 1,
    height: "16%",
    margin: "-6% 9%",
    overflow: "hidden",
    padding: "0% 16%",
  },
  AvatarOneImgStyle: {
    width: "78%",
    height: "94%",
  },
  AvatarTwoImgStyle: {
    width: "86%",
  },
  AvatarRunImgStyle: {
    width: "66%",
    transform: "translateY(6px)",
  },
  AvatarWinnerImgStyle: {
    width: "60%",
    transform: "translateY(8px)",
  },
  dividerStyle: {
    margin: "12% 5%",
    opacity: 0.7,
  },
  startGameStyleBtn: {
    background: "#4B7BFF 0% 0% no-repeat padding-box",
    boxShadow: "0px 3px 6px #00000029",
    border: "1px solid #70707026",
    borderRadius: "20px",
    opacity: 1,
    color: "white",
    fontSize: "12px",
    fontWeight: 400,
    fontFamily: "sans-serif",
    width: "60%",
    padding: "18px 0px",
    transform: "translateY(-39px)",
    "&:hover,&:focus": {
      background: "#4B7BFF 0% 0% no-repeat padding-box",
      boxShadow: "0px 3px 6px #00000029",
    },
  },
  arrowStyleOfBackBtn: {
    display: "grid",
    margin: "0.8% 3%",
},
playerstxt: {
    flex: "none",
    margin: "1% 6%",
}
};

export default detailAdditionPageStyle;
